version: '3'

services:
  postservice-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'postservice_db'
      MYSQL_USER: 'ikbeneenstudent'
      MYSQL_PASSWORD: 'ventieldopje24'
      MYSQL_ROOT_PASSWORD: 'ventieldopje24'
    ports:
      - '3306:3306'
    volumes:
      - postservice-db:/var/lib/mysql

  reviewservice-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'reviewservice_db'
      MYSQL_USER: 'ikbeneenstudent'
      MYSQL_PASSWORD: 'ventieldopje24'
      MYSQL_ROOT_PASSWORD: 'ventieldopje24'
    ports:
      - '3307:3306'
    volumes:
      - reviewservice-db:/var/lib/mysql

  commentservice-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'commentservice_db'
      MYSQL_USER: 'ikbeneenstudent'
      MYSQL_PASSWORD: 'ventieldopje24'
      MYSQL_ROOT_PASSWORD: 'ventieldopje24'
    ports:
      - '3308:3306'
    volumes:
      - commentservice-db:/var/lib/mysql

  frontend:
    build:
      context: ../../frontend-web
      dockerfile: Dockerfile
    container_name: frontend
    ports:
    - '4200:80'



  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management plugin port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


volumes:
  postservice-db:
  reviewservice-db:
  commentservice-db:
  rabbitmq-data:



